language: php
php:
  - 5.6
  - 7.1
  - 7.4

script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; then phpenv config-rm xdebug.ini; fi
  - composer install
  - ./vendor/bin/phpunit --coverage-text
